name: Flutter 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Install dependencies
        run: cd trelltech && flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test
